### PR TITLE
Point QBImagePicker to specific commit of flypaper fork

### LINKED ISSUE #118: iOS issues with QBImagePicker
QBImagePicker hasn't been updated in years and it appears the maintainer has no interest in merging in pull requests from the community.

QBImagePicker does not work correctly with iOS13 or with dark mode.  We have forked it [here](https://github.com/flypapertech/QBImagePicker) and have merged in the the two community pull requests to fix these issues.  We plan to maintain this fork for use with nativescript-camera-plus.  

For now we are using our own fork of nativescript-camera-plus so that we can depend on our fork of QBImagePicker.  Would you be open to a pull request that updates this repo to use our fork?

### PR DESCRIPTION
**Pull request by Logikgate**
Fixes #118

### CODE REVIEW

**Comment by bradmartin** [comment]
Merged, but can't get the demo project to actually run on iOS. Any chance you could look at that? Seems odd that this would break it though.

**Comment by Logikgate** [comment]
Thanks! And yes I will look at it tomorrow

**Comment by Logikgate** [comment]
Alright I took a look but it seems to be an issue only with the NS Core demo. The angular demo works fine.  I am admittedly not as familiar with debugging a NS Core app so what I did was:

- Reverted the pod change and tried to re-run the demo app. It failed with the same error.
- Tried updating all of the NS dependencies of the demo app along with the webpack config. This had no effect, same error.
- I noticed that the CI pipeline has been failing for some time and it appears to have the same error as well `Error: This value is not a native object.`.
- Updated the demo app to reference v3.0.6 of nativescript-camera-plus and that also errored with the same error
- Same with v3.0.5, did not work
- Updated the demo app to reference v3.0.4 and that worked. So it seems that something between 3.0.4 and 3.0.5 broke the NS Core demo

I was hoping to be able to fix it but I hope this at least is helpful for you to debug some more

**Comment by bradmartin** [comment]
yea that gives me some idea to poke around on it with. Thanks for the detailed info 👍 once I can get it working we'll get this published with the forked pod.

**Pull request merged**
